djangoProject/urls.py
from django.contrib import admin
from django.urls import path
from views_django_project import primera_vista, segunda_vista, fecha, calculo_edad, home, page_two

urlpatterns = [
    path('admin/', admin.site.urls),
    path('primera_vista/', primera_vista),
    path('segunda_vista/', segunda_vista),
    path('fecha/', fecha),
    path('edad/<int:edad>/<int:year>', calculo_edad),
    # el int hace que la edad introducida se trabaje como int. IMPORTANTE
    path('home/', home),
    path('pagetwo/', page_two)
]

example/example/urls.py
from django.contrib import admin
from django.urls import path
from orders.views import search_product, search, contact


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search_product/', search_product),
    path('search/', search),
    path('contact/', contact),
]

firstWeb/cartApp/urls.py
from django.urls import path
from .views import add_product, delete_product, delete_cart, remove_product

app_name = 'cart'
# para evitar problemas con los nombres dados a las urls

urlpatterns = [
    path('add/<int:product_id>/', add_product, name='add'),
    path('delete/<int:product_id>/', delete_product, name='delete'),
    path('remove/<int:product_id>/', remove_product, name='remove'),
    path('clear/', delete_cart, name='clear'),
]

firstWeb/firstWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webProject.urls')),
    # hacemos uno de estos por tantas apps tengamos en el proyecto.
    path('services/', include('servicesApp.urls')),
    path('blog/', include('blogApp.urls')),
    path('us/', include('contactApp.urls')),
    path('store/', include('storeApp.urls')),
    path('cart/', include('cartApp.urls')),
]

webProject01/WebApp/webProject01/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

firstWeb/storeApp/models.py
from django.db import models


# Create your models here.
class ProdCat(models.Model):
    cat_name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'productCategory'
        verbose_name_plural = 'productCategories'

    def __str__(self):
        return self.cat_name


class Product(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(ProdCat, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='store', null=True, blank=True)
    # necesario tener instalado Pillow para no tener errores con la migración
    price = models.FloatField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

firstWeb/storeApp/views.py
from django.shortcuts import render
from .models import Product


# Create your views here.

def store(request):
    product = Product.objects.all()
    return render(request, 'store/store.html', {'products': product})

#TODO: fix grid height in template (different card heights)

firstWeb/storeApp/templates/cart/widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store</title>
</head>

<body>
    <table class="table table-bordered" style="color: white; margin-top: 5px;">
        <thead>
            <tr>
                <th colspan="3" class="text-center"> Shopping Cart</th>
            </tr>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
        </thead>

        <tbody>
            {% if request.session.cart.items %}
                {% for key, value in request.session.cart.items %}
                    <tr class="text-center">
                        <td> {{ value.name }}</td>
                        <td> {{ value.quantity }}</td>
                        <td>
                            <a href="{% url 'cart:add' value.product_id %}" class="btn btn-sm btn-success">+</a>
                            <a href="{% url 'cart:remove' value.product_id %}" class="btn btn-sm btn-success">-</a>
                            <br>
                            {{ value.price }}$
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">
                        <div class="alert alert-info text-center">No items added</div>
                    </td>
                </tr>
            {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3"> Total: {{total_cart_value}} $ </td>
            </tr>
        </tfoot>
    </table>
</body>